auto:	          true

markdown:         rdiscount
pygments:         true
paginate:         6
permalink:        /:title

title:            ShiHongzhi's Blog
url:              http://shihongzhi.com
feed:             /atom.xml
author:
    name:         ShiHongzhi
    twitter:      twitter.com/shiboss
description:      "ShiHongzhi\'s Blog"
author_info:      <a href="http://shihongzhi.com/about">ShiHongzhi</a>

copyright:
    - Design by <a href="http://beiyuu.com/about" title="BeiYuu" target="_blank">BeiYuu</a> &copy; Copyright 2012
