auto: true

markdown: rdiscount
pygments: true
paginate: 6
permalink: /:title

title: shihongzhi.com
url: http://shihongzhi.com
feed: /atom.xml
author_info: <a href="http://shihongzhi.com/">shihongzhi</a>
