auto:	          true

markdown:         rdiscount
pygments:         true
paginate:         6
permalink:        /:title

title:            Shihongzhi自我修养
url:              http://shihongzhi.com
feed:             /atom.xml
author:
    name:         shihongzhi
    twitter:      twitter.com/shihognzhi
description:      "Shihongzhi的自我修养"
author_info:      <a href="http://shihognzhi.com/about">shihongzhi</a>

copyright:
    - Design by <a href="http://beiyuu.com/about" title="BeiYuu" target="_blank">BeiYuu</a> &copy; 2013
